Ddp 7085 disabling activity block
broadinstitute/ddp-study-server pull request #1064
Opened 2021-11-15 15:04 UTC by YuriyPavlovBI

DDP-7085 Extend API to support disabling activity block

2021-11-16 02:58 UTC, ssettipalli commented
wondering if this is something that can be handled from UI as one of cases. If checkbox checked , disable the edit button.
@MocanaAtBroad

2021-11-16 13:43 UTC, bskinner commented
> wondering if this is something that can be handled from UI as one of cases. If checkbox checked , disable the edit button and avoid the API changes @MocanaAtBroad

How would a front-end client know _that specific checkbox_ is special?

2021-11-29 19:23 UTC, ssettipalli submitted a review, later dismissed
looks ok to me

2021-11-29 19:39 UTC, bskinner requested changes, later dismissed

2021-11-29 19:39 UTC, bskinner commented on pepper-apis/docs/specification/src/components/schemas.yml
> +      description: whether block is enabled or not
What does `enabled` mean for a block? Adding a description of what changes with regards to the blocks behavior would be helpful.

2021-11-29 19:39 UTC, bskinner commented on pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiBlockEnabledExpression.java
> +            + " where be.block_id = :blockId and rev.end_date is null")
Will there be cases where `end_date` is set to a date in the future, but not `null`?

2021-11-29 21:02 UTC, YuriyPavlovBI commented on pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiBlockEnabledExpression.java
> +            + " where be.block_id = :blockId and rev.end_date is null")
I can imagine the situation you mentioned but for some reason it is made the same way for enabled expressions (see JdbiBlockExpression) so we did the same here. Revisions switch at the time we update the study. So, it seems ok for expressions.

2021-11-29 21:03 UTC, YuriyPavlovBI commented on pepper-apis/docs/specification/src/components/schemas.yml
> +      description: whether block is enabled or not
Added short description

2021-11-30 17:02 UTC, ssettipalli approved these changes

2021-11-30 18:17 UTC, merged