DDP-7392
broadinstitute/ddp-study-server pull request #1425
Opened 2022-04-12 12:33 UTC by leonidrakitin

https://broadinstitute.atlassian.net/browse/DDP-7392

2022-04-13 10:54 UTC, Trimax requested changes

2022-04-13 10:54 UTC, Trimax commented on pepper-apis/studybuilder-cli/src/main/java/org/broadinstitute/ddp/studybuilder/task/OsteoAboutChildV2.java
> -@Slf4j
Why did you remove Lombok's annotation?

2022-04-13 12:30 UTC, leonidrakitin commented on pepper-apis/studybuilder-cli/src/main/java/org/broadinstitute/ddp/studybuilder/task/OsteoAboutChildV2.java
> -@Slf4j
ccidentally deleted during a merge.

2022-04-14 13:58 UTC, Trimax commented on pepper-apis/studybuilder-cli/src/main/java/org/broadinstitute/ddp/studybuilder/task/OsteoAboutChildV2.java
> +    private static final Logger LOG = LoggerFactory.getLogger(OsteoAboutChildV2.class);
Please remove this line of the code.

I guess I have to put some details here. Slf4j annotation above the class says Lombok to inject logger instance automatically. So if you have your class annotated as Slf4j you can freely use logger without a direct definition. Like this: `log.info("Question ('CHILD_HISPANIC') successfully disabled");`

https://projectlombok.org/features/log

2022-04-19 05:14 UTC, archilsharashenidzebroad approved these changes
LGTM

2022-04-19 09:01 UTC, archilsharashenidzebroad approved these changes
LGTM

2022-04-20 12:48 UTC, closed without merging