Osteo Prequal updates
broadinstitute/ddp-study-server pull request #1665
Opened 2022-05-20 14:42 UTC by archilsharashenidzebroad

2022-05-20 16:12 UTC, leonidrakitin requested changes
I think that it would be better use UpdateTemplatesInPlace.traverseActivity()
You can find an example in this task - BrainConsentVersion2

2022-05-23 12:50 UTC, nsakande approved these changes
LGTM

2022-05-23 15:20 UTC, leonidrakitin approved these changes

2022-05-23 15:20 UTC, leonidrakitin commented on pepper-apis/studybuilder-cli/studies/osteo/patches/prequal-updates.conf
> +                {"language": "en", "text": "Let's Get Started"},
It also would be better if you will add variable at i18n/en.conf and use it here.

2022-05-23 15:33 UTC, merged