DDP-4551: Cross-study registration bug: Auth0 rule
broadinstitute/ddp-study-server pull request #176
Opened 2020-04-25 14:08 UTC by MocanaAtBroad

## Context
Fix involves changes Auth0 rule and frontt end . This PR contains modification to Auth0

## Checklist

- [X ] I have labeled the type of changes involved using the `C-*` labels.
- [X ] I have assessed potential risks and labeled using the `R-*` labels.
- [X ] I have considered error handling and alerts, and added `L-*` labels as needed.
- [X ] I have considered security and privacy, and added `I-*` labels as needed
- [ ] I have analyzed my changes for stability, fault tolerance, graceful degradation, performance bottlenecks and written a brief summary in this PR.
- [ ] If applicable, I have discussed the analytics needs at both a platform and study level with Product and instrumented code accordingly.
- [ ] If applicable, my UI/UX changes have passed muster with Product/Design via an over-the-shoulder review, screenshots, etc.

## FUD Score

_Overall, how are you feeling about these changes?_

- [ ] :relaxed: All good, business as usual!
- [X ] :sweat_smile: There might be some issues here
- [ ] :scream: I'm sweaty and nervous

## How do we demo these changes?
Walk through steps in bug report.

## Testing

- [ ] I have written automated positive tests
- [ ] I have written automated negative tests
- [ ] I have written zero automated tests but have poked around locally to verify proper functionality
- [ X] The jira ticket has acceptance criteria and QA has the needed information to test changes

## Release
Release of this feature requires updating the Auth0 rule, most likely through Auth0 management page.
- [ ] These changes require no special release procedures--just code!
- [X ] Releasing these changes requires special handling and I have documented the special procedures in the release plan document

2020-04-25 14:14 UTC, MocanaAtBroad commented on pepper-apis/auth0-config/rules/register-user-in-pepper.js
> +
Just 3 lines of code! But part of what was happening was that ALL token renewal requests ("Click Continue to extend your session") where generating calls to the pepper '/register route' . In the bug situation, the request contained a auth0 user id with the study id for the wrong study (the study in the other browser tab).

With this code, a token renewal never registers anyone. Note that we are counting on a new query parameter to identify the type of request.

2020-04-27 18:57 UTC, yufengwng requested changes
LGTM.

Re: disparity between checked-in code and what's on `dev`/`test`. I took a look and I see code is same as what's on `test`. `dev` has some new code that seems to relate to GAE. @MocanaAtBroad does that ring a bell?

Re: branching. `test` branch is a deployment branch (so is `staging` and `production` branches). We should not PR off of a deployment branch. Can you point your branch against `develop` so we can get this into the next release? Will approve after this is done.

2020-04-28 19:10 UTC, fat23cat approved these changes

2020-04-28 19:26 UTC, yufengwng approved these changes

2020-04-28 19:27 UTC, yufengwng commented
If this gets merged in for `v1.8.2` release, then please add instructions for updating Auth0 to `v1.8.2` release notes.

2020-04-28 19:32 UTC, merged