DDP-8196 add activity & section categorization feature during StudyBu…
broadinstitute/ddp-study-server pull request #1814
Opened 2022-06-20 11:39 UTC by LKapanad

- Create a schema file to store subforms and categories [DDP-8196-activity-groups.xml](https://github.com/broadinstitute/ddp-study-server/pull/1814/files#diff-074a920952023ea6ae789d3c62641d928150b7b7633796e580bdc923c9af1f57)
- Create config json serialization classes for subforms and categories: [FormGroupDef.java](https://github.com/broadinstitute/ddp-study-server/pull/1814/files#diff-8ae1709e7359e50ebbd35f4bf867f8cf1ad4c719e2c7a5e421112e35687de6c4), [ActivityCategoryDef.java](https://github.com/broadinstitute/ddp-study-server/pull/1814/files#diff-9d5e357e4bf9e9a833c32afa140bc3ef20436e9a73b73229a1117f98fabcc4f3)
- Update [FormSectionDef.java](https://github.com/broadinstitute/ddp-study-server/pull/1814/files#diff-5896bd1014b9553479388858fe5279bdcbe7273b08da4ca89bab2e1d0aa4311e) and [ActivityDef.java](https://github.com/broadinstitute/ddp-study-server/pull/1814/files#diff-b103c962dcdc4680864dd9c116dba4ed3227d31fd7319502e36ead8b15534c2d)  to store category & subform properties
- Create and update Dao classes to insert(during study building) and find (during ES export) subforms & categories. [ActivityCategoryDao.java](https://github.com/broadinstitute/ddp-study-server/pull/1814/files#diff-c5bf4f0f28d0cbfcb4533b97dc5e353e8363cdfdfc8f288bd12308ccded31d38) [ActivityGroupDao.java](https://github.com/broadinstitute/ddp-study-server/pull/1814/files#diff-bd7ac9e863ed306b2ca6421996278d714f2409bb4c29fec86f99dec4084baf2c) [FormActivityDao.java](https://github.com/broadinstitute/ddp-study-server/pull/1814/files#diff-5043bfc538037a9ee99d3104820cd13a0438dd31838b6919f58aeda964fa1f9e) [SectionBlockDao.java](https://github.com/broadinstitute/ddp-study-server/pull/1814/files#diff-6dc06799b50470b36bdd739ea5fe7f8858beed9fc87c10126aeec96aa6f5bd9c)

2022-06-21 18:11 UTC, MocanaAtBroad commented
Initial review looks like these are reasonable changes, but we should get rid of categorization of sections. We will be refactoring FON activities so that what is now a "subform" will be a separate activity. Simplifies everything, will be faster, allows us to track status properly etc. etc.

2022-06-21 18:12 UTC, MocanaAtBroad requested changes
See my comments on this PR and on Slack

2022-06-27 10:56 UTC, Trimax commented on pepper-apis/dss-core/src/main/java/org/broadinstitute/ddp/db/dao/ActivityCategoryDao.java
> +    Logger LOG = LoggerFactory.getLogger(ActivityCategoryDao.class);
As far as I see, the logger is not used, so let's remove this line

2022-06-27 10:56 UTC, Trimax commented on pepper-apis/dss-core/src/main/java/org/broadinstitute/ddp/db/dao/ActivityCategoryDao.java
> +    Long insertSubForm(@Bind("categoryId") Long categoryId, @Bind("parentFormId") Long parentFormId,
Shouldn't the name of the method be something like `insertCategoryGroup`?

2022-06-27 10:56 UTC, Trimax commented on pepper-apis/dss-core/src/main/java/org/broadinstitute/ddp/db/dao/ActivityCategoryDao.java
> +    long findByFormCode(String formCode);
I believe the name `findFormIdByCode` better reflects what it does.

2022-06-27 10:56 UTC, Trimax commented on pepper-apis/dss-core/src/main/java/org/broadinstitute/ddp/db/dto/ActivityFormGroupDto.java
> +public class ActivityFormGroupDto implements Serializable {
Instead of Getter & Setter let's use Data annotation

2022-06-27 10:56 UTC, Trimax commented on pepper-apis/dss-core/src/main/java/org/broadinstitute/ddp/model/activity/definition/ActivityCategoryDef.java
> +public class ActivityCategoryDef {
Same here. Instead of Getter & Setter let's use Data

2022-06-27 10:56 UTC, Trimax commented on pepper-apis/dss-core/src/main/java/org/broadinstitute/ddp/model/activity/definition/FormGroupDef.java
> +@Setter
Data instead of Getter & Setter

2022-06-27 10:56 UTC, Trimax commented on pepper-apis/dss-database/src/main/resources/db-changes/schema/DDP-8196-activity-groups.xml
> +            <column name="form_name" type="varchar(50)">
Are we sure that 50 symbols are enough for the form name? I have no idea what names potentially can be used, but something tells me they might be longer than 50 characters.

2022-06-27 20:54 UTC, MocanaAtBroad commented on pepper-apis/dss-database/src/main/resources/db-changes/schema/DDP-8196-activity-groups.xml
> +        <createTable tableName="category_group">
Recommend renaming to activity_category_group .

2022-06-27 20:54 UTC, MocanaAtBroad commented on pepper-apis/dss-database/src/main/resources/db-changes/schema/DDP-8196-activity-groups.xml
> +        </createTable>
Not seeing how splitting up category_group and activity_group into separate tables helps you out. Can this be just one table?

2022-06-27 20:54 UTC, MocanaAtBroad commented on pepper-apis/studybuilder-cli/src/main/java/org/broadinstitute/ddp/studybuilder/StudyBuilder.java
> +                    categoryEntry.getConfigList("subForms").stream().map(this::getSubForm).collect(Collectors.toList());
References to use of the word subforms is a little confusing to me as we generally don't refer to activities as forms (though I think maybe we should have called them forms! But it is what it is).
Maybe just call it activities?

2022-06-27 20:54 UTC, MocanaAtBroad commented on pepper-apis/dss-core/src/main/java/org/broadinstitute/ddp/db/dto/ActivityFormGroupDto.java
> +}
Surprised we need this code. Generally we just have needed custom serializers/deserializers when we have a difficult type conversion (e.g., string to date).
Please double check if really needed.

2022-06-30 03:38 UTC, ssettipalli commented
From what I understood:
Enrollment activity should be broken down into multiple activities (each section 1 activity)
Category and Group names might need translation support just like activity name and title if we end up adding that functionality.
We have support/place to add ActivityName, SecondName, Title & SubTitle
May be we can add category name into Name or Title and form name into SecondName or SubTitle if that works !!
Need to check API to see if SecondName is being used but Title/SubTitle are in use for sure.
If we don't want to take that approach: We might want to look into adding category and if needed group into:
i18n_activity_detail and that way we can have translations support for these new activity attributes.
Reg elastic:
Looks like even though we have ActivityName, Title/SubTitle looks like we are exporting only ActivityName into elastic: activity_definition elastic index. We can modify it to add other needed attributes like Title/SubTitle and if we add new attributes category and group can be added to elastic: activity_definition index.
cc @MocanaAtBroad @LKapanad

2022-07-06 15:44 UTC, MocanaAtBroad commented
Sampath: Are we saying here that all strings need to be translatable templates?

> From what I understood: Enrollment activity should be broken down into multiple activities (each section 1 activity) Category and Group names might need translation support just like activity name and title if we end up adding that functionality. We have support/place to add ActivityName, SecondName, Title & SubTitle May be we can add category name into Name or Title and form name into SecondName or SubTitle if that works !! Need to check API to see if SecondName is being used but Title/SubTitle are in use for sure. If we don't want to take that approach: We might want to look into adding category and if needed group into: i18n_activity_detail and that way we can have translations support for these new activity attributes. Reg elastic: Looks like even though we have ActivityName, Title/SubTitle looks like we are exporting only ActivityName into elastic: activity_definition elastic index. We can modify it to add other needed attributes like Title/SubTitle and if we add new attributes category and group can be added to elastic: activity_definition index. cc @MocanaAtBroad @LKapanad

2022-07-07 17:17 UTC, ssettipalli commented
looks like Marco accidentally closed the PR. Reopening

2022-07-07 17:20 UTC, MocanaAtBroad commented
> looks like Marco accidentally closed the PR. Reopening

Sorry! Those 2 buttons (Close and Comment are too close to each other and I have chubby klutzy fingers)!

2022-07-07 17:22 UTC, ssettipalli commented
@LKapanad :
For DSM to be able to use new activity category/group names, these activity level attributes should be exported to elastic.
Most likely DataExporter.java : exportActivityDefinitionsToElasticsearch should be modified to include these new attributes.
Looks like as of now only these activity level attributes are being exported : activityCode, activityName, activityVersion, parentActivityCode, displayOrder and status

2022-09-09 13:25 UTC, closed without merging