DDP-8465 | DSM Participant Export
broadinstitute/ddp-study-server pull request #2206
Opened 2022-08-26 12:01 UTC by Anzori-Ghurtchumelia

## Context

There are multiple tickets associated with this bug fix.

The problem: previously we would not export `dsm.participant` in ES when the participant was created for the first time, thereby it would create issues associated with multiple `Patch` requests since majority of them require `dsm.participant.participantId` to be available on the client side which is used as `parentId` for `Patch` request.

Solution: export `dsm.participant` when the participant is created so that every participant has `dsm.participant.participantId` available in ES and therefore on the client side too.

Tech details:

- Add `ParticipantExportPayload` as a DTO class which holds the dependencies for the specific `Exportable` instances.
- Extend `Participant` and create `NewOsteoParticipant` for exporting data for `osteo2` under `dsm.newOsteoParticipant`.
- Establish `ElasticSearchParticipantExporterFactory` which would build an instance of `Exportable` based on the `instance_name` of the study.
- Create two implementations for `Exportable`:
  - `NewOsteoParticipantExporter` for `New Osteo` study which should export `dsm.participant` instead of `dsm.participant`
  - `DefaultParticipantExporter` for any other studies which exports `dsm.participant`
- Modify the `DDPMedicalRecordDataRequest` based on changes.
- Write unit tests   

## Checklist

- [ ] I have labeled the type of changes involved using the `C-*` labels.
- [ ] I have assessed potential risks and labeled using the `R-*` labels.
- [ ] I have considered error handling and alerts, and added `L-*` labels as needed.
- [ ] I have considered security and privacy, and added `I-*` labels as needed
- [ ] I have analyzed my changes for stability, fault tolerance, graceful degradation, performance bottlenecks and written a brief summary in this PR.
- [ ] If applicable, I have discussed the analytics needs at both a platform and study level with Product and instrumented code accordingly.
- [ ] If applicable, my UI/UX changes have passed muster with Product/Design via an over-the-shoulder review, screenshots, etc.

_If unsure or need help with any of the above items, add the `help wanted` label. For items that starts with `If applicable`, if it is not applicable, check it off and add `n/a` in front._

## FUD Score

_Overall, how are you feeling about these changes?_

- [ ] :relaxed: All good, business as usual!
- [ ] :sweat_smile: There might be some issues here
- [ ] :scream: I'm sweaty and nervous

## How do we demo these changes?

_How does one observe these changes in a deployed system? Note that **user visible** encompasses many personas--not just patients and study staff, but also ops duty, your fellow devs, compliance, etc._

- [ ] They are user-visible in dev as a regular user journey and require no additional instructions.
- [ ] Getting dev into a state where this is user-visible requires some tech fiddling. I have documented these steps in the related ticket.
- [ ] Requires other features before it's human visible. I have documented the blocking issues in jira.
- [ ] I have no idea how to demo this. Please help me!

## Testing

- [ ] I have written automated positive tests
- [ ] I have written automated negative tests
- [ ] I have written zero automated tests but have poked around locally to verify proper functionality
- [ ] The jira ticket has acceptance criteria and QA has the needed information to test changes

## Release

- [ ] These changes require no special release procedures--just code!
- [ ] Releasing these changes requires special handling and I have documented the special procedures in the release plan document

2022-08-26 13:08 UTC, gmakharat approved these changes

2022-08-26 14:40 UTC, SimoneMaiwald requested changes
Please add steps to reproduce/check the fix on DSM UI

2022-08-29 13:10 UTC, SimoneMaiwald commented on pepper-apis/dsm-core/src/main/java/org/broadinstitute/dsm/util/DDPMedicalRecordDataRequest.java
> +            int participantId             = new ParticipantDao().create(participantDto);
can you remove these whitespaces, please

2022-08-29 13:13 UTC, SimoneMaiwald approved these changes

2022-08-29 14:54 UTC, merged