[DSM] Update appengine app.yaml for Dev env
broadinstitute/ddp-study-server pull request #2705
Opened 2023-10-13 15:40 UTC by aweng98

## Context

_Say a few words about the bigger picture beyond this PR. How do your changes improve life for our users? Link directly to the jira ticket (just type "DDP-..." and it'll automatically link) to help your teammates quickly get up to speed on the motivation for these changes._

## Checklist

- [ ] I have labeled the type of changes involved using the `C-*` labels.
- [ ] I have assessed potential risks and labeled using the `R-*` labels.
- [ ] I have considered error handling and alerts, and added `L-*` labels as needed.
- [ ] I have considered security and privacy, and added `I-*` labels as needed
- [ ] I have analyzed my changes for stability, fault tolerance, graceful degradation, performance bottlenecks and written a brief summary in this PR.
- [ ] If applicable, I have discussed the analytics needs at both a platform and study level with Product and instrumented code accordingly.
- [ ] If applicable, my UI/UX changes have passed muster with Product/Design via an over-the-shoulder review, screenshots, etc.

_If unsure or need help with any of the above items, add the `help wanted` label. For items that starts with `If applicable`, if it is not applicable, check it off and add `n/a` in front._

## FUD Score

_Overall, how are you feeling about these changes?_

- [ ] :relaxed: All good, business as usual!
- [ ] :sweat_smile: There might be some issues here
- [ ] :scream: I'm sweaty and nervous

## How do we demo these changes?

_How does one observe these changes in a deployed system? Note that **user visible** encompasses many personas--not just patients and study staff, but also ops duty, your fellow devs, compliance, etc._

- [ ] They are user-visible in dev as a regular user journey and require no additional instructions.
- [ ] Getting dev into a state where this is user-visible requires some tech fiddling. I have documented these steps in the related ticket.
- [ ] Requires other features before it's human visible. I have documented the blocking issues in jira.
- [ ] I have no idea how to demo this. Please help me!

## Testing

- [ ] I have added regression test labels to the jira ticket
- [ ] I have added verification steps to the jira ticket
- [ ] I have written automated positive tests
- [ ] I have written automated negative tests
- [ ] I have written zero automated tests but have poked around locally to verify proper functionality
- [ ] The jira ticket has acceptance criteria and QA has the needed information to test changes

## Release

- [ ] These changes require no special release procedures--just code!
- [ ] Releasing these changes requires special handling and I have documented the special procedures in the release plan document

2023-10-13 15:46 UTC, aweng98 commented on pepper-apis/config/DataDonationPlatform.yaml.ctmpl
> +  target_cpu_utilization: 0.95
`target_cpu_utilization`: default value is 0.6.

2023-10-13 15:46 UTC, aweng98 commented on pepper-apis/config/DataDonationPlatform.yaml.ctmpl
> +  target_throughput_utilization: 0.95
`target_throughput_utilization`: default value is 0.6.

2023-10-13 15:46 UTC, aweng98 commented on pepper-apis/config/DataDonationPlatform.yaml.ctmpl
> +  max_concurrent_requests: 80
`max_concurrent_requests`: default value is 10.

2023-10-13 15:46 UTC, aweng98 commented on pepper-apis/config/DataDonationPlatform.yaml.ctmpl
> +  max_pending_latency: 30s
`max_pending_latency`: default is 10 seconds.

2023-10-13 16:29 UTC, Rinchan20 approved these changes

2023-10-16 12:08 UTC, zyme requested changes
I have concerns that this will lead to unexpected behavior across dev/test/staging as well as prod.  We should have the same infrastructure settings across all environments.  Our prior experience tuning automatic scaling in GAE did not turn out well.  Let's discuss whether we want to give this another try.

2023-11-30 19:43 UTC, closed without merging