PEPPER-665 . participant list down Race's ethnicity (nested options) fix
broadinstitute/ddp-study-server pull request #2927
Opened 2024-08-16 17:22 UTC by ssettipalli

PEPPER-665

Include RACE ethnicity which are selected nested options of the Picklist question in download

2024-08-16 18:05 UTC, ssettipalli commented
[
[DataDictionary.xlsx](https://github.com/user-attachments/files/16640234/DataDictionary.xlsx)
[Participant-2024-08-16.xlsx](https://github.com/user-attachments/files/16640235/Participant-2024-08-16.xlsx)
[DataDictionary-2.xlsx](https://github.com/user-attachments/files/16640240/DataDictionary-2.xlsx)
[Participant-2024-08-16-2.xlsx](https://github.com/user-attachments/files/16640241/Participant-2024-08-16-2.xlsx)
](url)

2024-08-21 01:45 UTC, denniscunningham requested changes
There is test infrastructure in place for this code already, so it would be great to see some tests that verify this new behavior.

2024-08-21 18:13 UTC, ssettipalli commented on pepper-apis/dsm-core/src/test/resources/elastic/lmsAboutYouActivity.json
> +[
activity instance / survey response for testing

2024-08-21 18:13 UTC, ssettipalli commented on pepper-apis/dsm-core/src/test/resources/elastic/lmsAboutYouActivityDef.json
> +{
activity definition

2024-08-21 18:13 UTC, ssettipalli commented on pepper-apis/dsm-core/src/test/resources/elastic/participantListAboutYouRaceDownload.json
> +{
filters

2024-08-21 18:15 UTC, ssettipalli commented
> There is test infrastructure in place for this code already, so it would be great to see some tests that verify this new behavior.

Added test case to DownloadParticipantListServiceTest which checks for nested options behavior in elastic and download

2024-08-21 20:59 UTC, denniscunningham approved these changes

2024-08-22 01:09 UTC, merged