DDP-5114-gae-service-to-log: detect GAE service name from env var GAE…
broadinstitute/ddp-study-server pull request #576
Opened 2020-12-30 14:39 UTC by evgeniipr

…_SERVICE; add to log message via MDC GAEinstance:GAEservice pair (in DataDonationPlatform and Housekeeping).

Defined latest version of Mockito where static methods mocking possible; in unit tests mock env variables setting via SystemUtil methods mocking.

## Context

Modified HostUtil.java: added method to get GAE service name from env variable GAE_SERVICE. 
Added method HostUtil.putGAEInstanceAndGAEServiceToMDC() which puts a pair of detected GAE instance/service to logging MDC variable "GAEInstanceAndService".
It's added into logback.xml pattern:
%d{HH:mm:ss.SSS} %X{GAEInstanceAndService} %X{LogBreadCrumb} ...
In both services (DataDonationPlatform, Housekeeping) method HostUtil.putGAEInstanceAndGAEServiceToMDC() called at the beginning.
In DDP-5114 is described how these changed can be detected (in DDP log files).

## Checklist

- [x ] I have labeled the type of changes involved using the `C-*` labels.
- [x ] I have assessed potential risks and labeled using the `R-*` labels.
- [x ] I have considered error handling and alerts, and added `L-*` labels as needed.
- [x ] I have considered security and privacy, and added `I-*` labels as needed
- [x ] I have analyzed my changes for stability, fault tolerance, graceful degradation, performance bottlenecks and written a brief summary in this PR.
- [ x] If applicable, I have discussed the analytics needs at both a platform and study level with Product and instrumented code accordingly.
- [x ] If applicable, my UI/UX changes have passed muster with Product/Design via an over-the-shoulder review, screenshots, etc.

__Help wanted__. 
The following changes needs to be discussed/approved:
* HostUtil.putGAEInstanceAndGAEServiceToMDC() called for pepper backend and Housekeeping but not for DSM. Should I create separate ticket for DSM? 
* Is it ok to put this new data in log message like this: %d{HH:mm:ss.SSS} %X{GAEInstanceAndService} %X{LogBreadCrumb} ?
* The GAE_INSTANCE/host added to StackDriverMetricsTracker: resourceLabels.put("node_id", HostUtil.getGAEInstanceOrHostName());
Should it be set GAE_INSTANCE/GAE_SERVICE pair their either?
* artifact org.mockito version upgraded to 3.6.28 in order to use static mocking - could it cause any problems?

## FUD Score

_Overall, how are you feeling about these changes?_

- [ ] :relaxed: All good, business as usual!
- [ x] :sweat_smile: There might be some issues here
- [ ] :scream: I'm sweaty and nervous

## How do we demo these changes?

_How does one observe these changes in a deployed system? Note that **user visible** encompasses many personas--not just patients and study staff, but also ops duty, your fellow devs, compliance, etc._

- [ ] They are user-visible in dev as a regular user journey and require no additional instructions.
- [x ] Getting dev into a state where this is user-visible requires some tech fiddling. I have documented these steps in the related ticket.
- [ ] Requires other features before it's human visible. I have documented the blocking issues in jira.
- [ ] I have no idea how to demo this. Please help me!

## Testing

- [x ] I have written automated positive tests
- [x ] I have written automated negative tests
- [ ] I have written zero automated tests but have poked around locally to verify proper functionality
- [ x] The jira ticket has acceptance criteria and QA has the needed information to test changes

## Release

- [x ] These changes require no special release procedures--just code!
- [ ] Releasing these changes requires special handling and I have documented the special procedures in the release plan document

2021-01-05 18:17 UTC, yufengwng requested changes
I have some concerns:

1. I don't understand why we need to do this. GCP Logging already tracks which GAE service a log entry comes from. For example, in the GCP Log Viewer you can query with `resource.labels.module_id="pepper-backend"` to find logs from the `pepper-backend` service. So I don't think we need to add yet another parameter to the log format.
2. If I understand the ticket, I believe what @MocanaAtBroad wants is to have the GAE service name show up in the _Slack alerts_. What this means to me is we should change `SlackAppender` to read the `GAE_SERVICE` env variable instead of fiddling with `HostUtil` or `MDC`.

2021-01-05 19:29 UTC, zyme commented
I share @yufengwng's concerns.  I think I didn't write the ticket very well--my apologies!  The key thing is indeed to get the service passed through to slack.

2021-01-05 21:08 UTC, MocanaAtBroad reviewed
Yeah. I think it will be easy for Evgenii to fix though. He figured out how to get the GCP metadata. Looks like just some tweaks to the SlackAppender ought to do trick.

2021-01-05 21:08 UTC, MocanaAtBroad commented on pepper-apis/src/main/java/org/broadinstitute/ddp/environment/HostUtil.java
> +    @VisibleForTesting
Never seen this annotation before. Nice!

2021-01-11 13:27 UTC, evgeniipr commented
Hi!
So, it no need to modify HostUtil and just toread GAE_INSTANCE directly in SlackAppender and put it at the beginning of the message?

2021-01-19 15:22 UTC, zyme approved these changes

2021-01-19 20:18 UTC, yufengwng approved these changes
Looks about right.

2021-01-20 11:25 UTC, merged