DDP-6743 . Add brain cancer to keywords/options
broadinstitute/ddp-study-server pull request #952
Opened 2021-08-06 17:07 UTC by ssettipalli

fix for https://broadinstitute.atlassian.net/browse/DDP-6743

2021-08-11 15:43 UTC, MocanaAtBroad commented
Let's shelve these changes. The "keyword" idea is more of a feature and less a configuration problem. Have agreed to CMI to revisit idea post-launch.

2021-08-11 15:43 UTC, MocanaAtBroad requested changes
Added comment. Let's not merge this PR.

2021-08-11 15:58 UTC, evgeniipr approved these changes

2022-11-23 15:08 UTC, Trimax commented
Discussed with @zyme. Not going to be merged.

2022-11-23 15:08 UTC, closed without merging